// <auto-generated />
using System;
using Medismart.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Medismart.Migrations
{
    [DbContext(typeof(MedismartContext))]
    [Migration("20210122064931_seeddata")]
    partial class seeddata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Medismart.Data.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Accomodation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Alias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Checkin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EquipmentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GuestChild")
                        .HasColumnType("int");

                    b.Property<int?>("GuestMiddle")
                        .HasColumnType("int");

                    b.Property<int?>("GuestOld")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Pet")
                        .HasColumnType("bit");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<string>("RequiredService")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SlideOut")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Accomodation = "RV",
                            Alias = "Mr",
                            CheckOut = new DateTime(2021, 1, 22, 6, 49, 30, 740, DateTimeKind.Utc).AddTicks(5970),
                            Checkin = new DateTime(2021, 1, 22, 6, 49, 30, 740, DateTimeKind.Utc).AddTicks(5103),
                            Comments = "This is comment",
                            Email = "Medismartsgmail.com",
                            EquipmentType = "Hydro",
                            FirstName = "Hambal",
                            GuestChild = 1,
                            GuestMiddle = 1,
                            GuestOld = 1,
                            LastName = "Tella",
                            Pet = false,
                            Phone = 123455,
                            RequiredService = "water",
                            SlideOut = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
